
project_id = "jqjjolwssfybybvqclpo"

[auth]
enabled = true
site_url = "http://localhost:3000"

[functions.enhanced-crawl-website]
verify_jwt = false

[functions.background-job-processor]
verify_jwt = false

[functions.child-job-processor]
verify_jwt = false

[functions.process-source-pages]
verify_jwt = false

[functions.workflow-job-processor]
verify_jwt = false
