
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyanwfhlxhitazaouemg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5YW53ZmhseGhpdGF6YW91ZW1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0OTA1MDksImV4cCI6MjA2MzA2NjUwOX0.NSMg5aMxaO7-W4F28HurXcgHuXpgaUVpV53Hhjfkj_w";

// Create the base Supabase client without session
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Create a function to get an authenticated client with the session token
export const getAuthenticatedClient = (accessToken: string) => {
  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      headers: {
        Authorization: `Bearer ${accessToken}`,
      }
    }
  });
};
